### ISSUE TITLE
Escrever a premissa do jogo

### ISSUE THREAD

**Issue by ghost** [boiada-da-cara-preta/jogo-web#1]
Para exercício, fazer de pelo menos a premissa de 10 jogos bastante conhecidos: Candy Crush, Tetris etc. Ao final, gerar um arquivo no formato Markdown ou HTML com a premissa do jogo a ser desenvolvido.

**Comment by ghost** [comment]
Equipes:
- [X] [mirabolante](https://github.com/mirabolante)

**Comment by ghost** [comment]
O _commit_ 7c0b65659d3490a9c416b3697da23bf9084102f8 atende a tarefa.

**Comment by boidacarapreta** [comment]
Equipes:
- [X] [mirabolante](https://github.com/mirabolante)
- [X] [Falarya Brawl](https://github.com/falarya-brawl/)

**Comment by ghost** [comment]
Os universos dos dois jogos estão integrados. De um lado, Matias quer fugir da ARCa 20202, enquanto de outro lado [Lola tenta achar o seu irmão](https://github.com/boidacarapreta/cab20202/issues/4)...
